name: format
description: An extension method format() for format strings like one in Python.
version: 1.0.1-nullsafety.0
homepage: https://github.com/vi-k/format

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  characters: ^1.1.0-nullsafety.5
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0-nullsafety.12
